### ISSUE TITLE
Sometimes empty/null values on the MQTT broker

### ISSUE THREAD

**Issue by fluppie** [dingo35/Sensorbox-2#2]
**Describe the bug**
Sometimes an empty/null value is posted to the MQTT broker.
![afbeelding](https://github.com/user-attachments/assets/13a3c612-9d9f-47d8-a349-5d0cd9e60e46)

![afbeelding](https://github.com/user-attachments/assets/89901466-c0d8-42db-a162-bd34bfa741fb)

**Upload your config**
Press the "raw" button in the SmartEVSE webserver and upload the json settings file, so we can look at your configuration.
`<html><body>
<div id="content"><div class="tabs tabs-tall "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="JSON filteren" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">
  |  
-- | --
version | "21:14:10 @Oct 30 2024"
serialnr | 100321
smartevse_host | ""
wifi |  
status | "WL_CONNECTED"
ssid | "MyWiFiSSID"
rssi | -32
bssid | "F0:9F:C2:F4:01:56"
settings |  
mains_meter | "Sensorbox"
evse |  
temp | 0
ev_meter |  
description | "Disabled"
currents |  
TOTAL | 0
L1 | 0
L2 | 0
L3 | 0
mqtt |  
host | "verybigsecret.com"
port | 1883
topic_prefix | "Sensorbox/100321"
username | "secretuser"
password_set | true
status | "Connected"
phase_currents |  
TOTAL | 34
L1 | 34
L2 | 0
L3 | 0
last_data_update | 1730322503

</div></div></div></div>
</body>
</html>`

**To Reproduce**
Just flash the new Sensorbox fw, connect to your MQTT broker and watch the traffic in MQTT Explorer

**Expected behavior**
No null/empty values, maybe from time to time, but now this is almost 50% of the time I get these.

**Comment by dingo35** [comment]
So are you using P1 connection or CT clamps?

**Comment by fluppie** [comment]
CT Clamp, Only on L1.
But for some weird reason, when I now launch mqtt explorer... No more nulls
![afbeelding](https://github.com/user-attachments/assets/b19245d2-deb5-4c1a-b0e0-1358271025e7)

**Comment by dingo35** [comment]
Ok I am not able to test in real life conditions, but Michael Stegen has had this version running for some time now without problems, so I will be releasing this version (it is added functionality so even if it has a bug in it, nobody sacrifices anything....)

**Comment by fluppie** [comment]
Looks like it's working well (FW built on 30/10/2024)... Did some periodic checks. Maybe something after the initial fw upgrade that dissappeared after a reboot?
